---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
    - ssh_identity_file

- hosts: target
  gather_facts: no

  pre_tasks:
    - name: install python
      raw: sudo apt update && sudo apt install -y python-minimal
      tags: [infrastructure]

- hosts: target
  roles:
    - role: angstwad.docker_ubuntu
      tags: [infrastructure]
    - role: git
      tags: [infrastructure]
    - docker_login
    - deploy

